title: InandOutsidepixce
description: 살아가는 방법을 다룹니다
author: insidepixce
avatar: /logo.png
email: insidepixce@gmail.com
skin: sunrise
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 4

disqus:
  shortname: insidepixce


# Uncomment the below line and set the tracking ID for enabling Google Analytics
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.png
social:
  name: insidepixce
  links:
    - https://www.instagram.com/insidepixce/
    - https://github.com/insidepixce
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: conflict
      tag: 
        - react

disqus:
  comments: true
  shortname: "mylog-3" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  